[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="author.name") %}
{% for commit in commits %}
{{ commit.author.timestamp | date(format="%Y-%m-%d") }}  {{ commit.author.name }}  <{{ commit.author.email }}>

\t* {{ commit.message | trim }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
