[changelog]
header = ""
body = """
{% for author, commits in commits | group_by(attribute="author.name") %}
{{ commits[0].author.timestamp | date(format="%Y-%m-%d") }}  {{ author }}  <{{ commits[0].author.email }}>
{% for commit in commits %}
\t* {{ commit.message | trim }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}

{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
sort_commits = "oldest"
